// Code generated by protoc-gen-go.
// source: protobuf/reply.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protobuf/reply.proto
	protobuf/request.proto

It has these top-level messages:
	Reply
	Request
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Reply struct {
	NewData []byte `protobuf:"bytes,1,opt,name=NewData,proto3" json:"NewData,omitempty"`
}

func (m *Reply) Reset()                    { *m = Reply{} }
func (m *Reply) String() string            { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()               {}
func (*Reply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*Reply)(nil), "protocol.Reply")
}

var fileDescriptor0 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x4f, 0x2a, 0x4d, 0xd3, 0x2f, 0x4a, 0x2d, 0xc8, 0xa9, 0xd4, 0x03, 0x73, 0x85, 0x38, 0xc0,
	0x54, 0x72, 0x7e, 0x8e, 0x92, 0x22, 0x17, 0x6b, 0x10, 0x48, 0x42, 0x48, 0x82, 0x8b, 0xdd, 0x2f,
	0xb5, 0xdc, 0x25, 0xb1, 0x24, 0x51, 0x82, 0x51, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc6, 0x4d, 0x62,
	0x03, 0x2b, 0x36, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6b, 0x4d, 0xbb, 0xe7, 0x4b, 0x00, 0x00,
	0x00,
}
