// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package factory

import (
	"github.com/danielkrainas/sake/pkg/service"
)

// Injectors from wire.go:

func Coordinator(ctx RootContext, config *service.Config) (service.CoordinatorService, error) {
	context, err := InitializeLoggingContext(ctx, config)
	if err != nil {
		return nil, err
	}
	hubConnector, err := InitializeHub(context)
	if err != nil {
		return nil, err
	}
	coordinatorService, err := InitializeCoordinator(context, hubConnector)
	if err != nil {
		return nil, err
	}
	return coordinatorService, nil
}
